name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Release
      run: dotnet publish --no-restore
    
    - name: Create tag artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}
        path: Release
